# Generated by Django 6.0.6 on 2026-06-13 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.BigAutoField(db_column='IdUsuario', primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(db_column='NombreUsuario', max_length=100, unique=True)),
                ('contra_encriptada', models.CharField(db_column='ContraEncriptada', max_length=255)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True, db_column='FechaAlta')),
                ('activo', models.BooleanField(db_column='Activo', default=True)),
            ],
            options={
                'db_table': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='CarpetaArchivo',
            fields=[
                ('id_carpeta', models.BigAutoField(db_column='IdCarpeta', primary_key=True, serialize=False)),
                ('nombre_carpeta', models.CharField(blank=True, db_column='NombreCarpeta', max_length=255, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='FechaCreacion')),
            ],
            options={
                'db_table': 'CarpetaArchivos',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(db_column='IdCategoria', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=150, unique=True)),
                ('descripcion', models.TextField(blank=True, db_column='Descripcion', null=True)),
            ],
            options={
                'db_table': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_estado', models.AutoField(db_column='IdEstado', primary_key=True, serialize=False)),
                ('nombre_estado', models.CharField(db_column='NombreEstado', max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, db_column='Descripcion', null=True)),
            ],
            options={
                'db_table': 'Estados',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(db_column='IdRol', primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(db_column='NombreRol', max_length=100, unique=True)),
            ],
            options={
                'db_table': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='TagDenuncia',
            fields=[
                ('id_tag', models.AutoField(db_column='IdTag', primary_key=True, serialize=False)),
                ('nombre_tag', models.CharField(db_column='NombreTag', max_length=100, unique=True)),
            ],
            options={
                'db_table': 'TagsDenuncia',
            },
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id_usuario', models.OneToOneField(db_column='IdUsuario', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.usuario')),
                ('legajo', models.CharField(blank=True, db_column='Legajo', max_length=50, null=True, unique=True)),
                ('fecha_ingreso', models.DateField(blank=True, db_column='FechaIngreso', null=True)),
                ('rol_admin', models.CharField(blank=True, db_column='RolAdmin', max_length=50, null=True)),
            ],
            options={
                'db_table': 'Administradores',
            },
        ),
        migrations.CreateModel(
            name='InfoUsuario',
            fields=[
                ('id_usuario', models.OneToOneField(db_column='IdUsuario', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.usuario')),
                ('email', models.CharField(db_column='Email', max_length=255, unique=True)),
                ('domicilio', models.CharField(blank=True, db_column='Domicilio', max_length=255, null=True)),
                ('dni', models.CharField(blank=True, db_column='DNI', max_length=50, null=True, unique=True)),
                ('telefono', models.CharField(blank=True, db_column='Telefono', max_length=50, null=True)),
            ],
            options={
                'db_table': 'InfoUsuarios',
            },
        ),
        migrations.CreateModel(
            name='PreferenciaUsuario',
            fields=[
                ('id_usuario', models.OneToOneField(db_column='IdUsuario', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.usuario')),
                ('recibir_emails', models.BooleanField(db_column='RecibirEmails', default=True)),
                ('idioma', models.CharField(db_column='Idioma', default='es', max_length=10)),
                ('zona_horaria', models.CharField(blank=True, db_column='ZonaHoraria', max_length=50, null=True)),
            ],
            options={
                'db_table': 'PreferenciasUsuario',
            },
        ),
        migrations.CreateModel(
            name='AuditCambio',
            fields=[
                ('id_audit', models.BigAutoField(db_column='IdAudit', primary_key=True, serialize=False)),
                ('tabla', models.CharField(blank=True, db_column='Tabla', max_length=100, null=True)),
                ('id_registro', models.CharField(blank=True, db_column='IdRegistro', max_length=100, null=True)),
                ('operacion', models.CharField(blank=True, db_column='Operacion', max_length=20, null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, db_column='FechaHora')),
                ('detalle_antes', models.JSONField(blank=True, db_column='DetalleAntes', null=True)),
                ('detalle_despues', models.JSONField(blank=True, db_column='DetalleDespues', null=True)),
                ('id_usuario', models.ForeignKey(blank=True, db_column='IdUsuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.usuario')),
            ],
            options={
                'db_table': 'AuditCambios',
            },
        ),
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id_archivo', models.BigAutoField(db_column='IdArchivo', primary_key=True, serialize=False)),
                ('nombre_archivo', models.CharField(blank=True, db_column='NombreArchivo', max_length=255, null=True)),
                ('ruta', models.CharField(blank=True, db_column='Ruta', max_length=1024, null=True)),
                ('tipo_mime', models.CharField(blank=True, db_column='TipoMime', max_length=100, null=True)),
                ('tamano_bytes', models.BigIntegerField(blank=True, db_column='TamanoBytes', null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, db_column='FechaSubida')),
                ('id_carpeta', models.ForeignKey(db_column='IdCarpeta', on_delete=django.db.models.deletion.CASCADE, to='api.carpetaarchivo')),
            ],
            options={
                'db_table': 'Archivos',
            },
        ),
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id_denuncia', models.BigAutoField(db_column='IdDenuncia', primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, db_column='Titulo', max_length=255, null=True)),
                ('descripcion', models.TextField(blank=True, db_column='Descripcion', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='FechaCreacion')),
                ('id_categoria', models.ForeignKey(blank=True, db_column='IdCategoria', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.categoria')),
                ('id_usuario', models.ForeignKey(db_column='IdUsuario', on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
                ('estado_actual', models.ForeignKey(blank=True, db_column='EstadoActualId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='denuncias_estado_actual', to='api.estado')),
            ],
            options={
                'db_table': 'Denuncias',
            },
        ),
        migrations.AddField(
            model_name='carpetaarchivo',
            name='id_denuncia',
            field=models.ForeignKey(db_column='IdDenuncia', on_delete=django.db.models.deletion.CASCADE, to='api.denuncia'),
        ),
        migrations.CreateModel(
            name='LogAcceso',
            fields=[
                ('id_log', models.BigAutoField(db_column='IdLog', primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, db_column='FechaHora')),
                ('ip', models.CharField(blank=True, db_column='IP', max_length=50, null=True)),
                ('user_agent', models.TextField(blank=True, db_column='UserAgent', null=True)),
                ('resultado', models.CharField(blank=True, db_column='Resultado', max_length=50, null=True)),
                ('id_usuario', models.ForeignKey(blank=True, db_column='IdUsuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.usuario')),
            ],
            options={
                'db_table': 'LogsAcceso',
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id_notificacion', models.BigAutoField(db_column='IdNotificacion', primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, db_column='Tipo', max_length=50, null=True)),
                ('contenido', models.TextField(blank=True, db_column='Contenido', null=True)),
                ('leida', models.BooleanField(db_column='Leida', default=False)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, db_column='FechaEnvio')),
                ('id_usuario', models.ForeignKey(db_column='IdUsuario', on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
            options={
                'db_table': 'Notificaciones',
            },
        ),
        migrations.CreateModel(
            name='TelefonoUsuario',
            fields=[
                ('id_telefono', models.BigAutoField(db_column='IdTelefono', primary_key=True, serialize=False)),
                ('telefono', models.CharField(blank=True, db_column='Telefono', max_length=50, null=True)),
                ('tipo', models.CharField(blank=True, db_column='Tipo', max_length=50, null=True)),
                ('principal', models.BooleanField(db_column='Principal', default=False)),
                ('id_usuario', models.ForeignKey(db_column='IdUsuario', on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
            options={
                'db_table': 'TelefonosUsuario',
            },
        ),
        migrations.CreateModel(
            name='EstadoDenuncia',
            fields=[
                ('id_estado_denuncia', models.BigAutoField(db_column='IdEstadoDenuncia', primary_key=True, serialize=False)),
                ('comentario_admin', models.TextField(blank=True, db_column='ComentarioAdmin', null=True)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True, db_column='FechaCambio')),
                ('id_denuncia', models.ForeignKey(db_column='IdDenuncia', on_delete=django.db.models.deletion.CASCADE, to='api.denuncia')),
                ('id_estado', models.ForeignKey(db_column='IdEstado', on_delete=django.db.models.deletion.CASCADE, to='api.estado')),
                ('id_admin', models.ForeignKey(blank=True, db_column='IdAdmin', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.administrador')),
            ],
            options={
                'db_table': 'EstadoDenuncias',
            },
        ),
        migrations.CreateModel(
            name='DenunciaTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_denuncia', models.ForeignKey(db_column='IdDenuncia', on_delete=django.db.models.deletion.CASCADE, to='api.denuncia')),
                ('id_tag', models.ForeignKey(db_column='IdTag', on_delete=django.db.models.deletion.CASCADE, to='api.tagdenuncia')),
            ],
            options={
                'db_table': 'DenunciaTags',
                'constraints': [models.UniqueConstraint(fields=('id_denuncia', 'id_tag'), name='uq_dt_denuncia_tag')],
            },
        ),
        migrations.CreateModel(
            name='UsuarioRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_rol', models.ForeignKey(db_column='IdRol', on_delete=django.db.models.deletion.CASCADE, to='api.rol')),
                ('id_usuario', models.ForeignKey(db_column='IdUsuario', on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
            options={
                'db_table': 'UsuariosRoles',
                'constraints': [models.UniqueConstraint(fields=('id_usuario', 'id_rol'), name='uq_ur_usuario_rol')],
            },
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id_voto', models.BigAutoField(db_column='IdVoto', primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, db_column='Descripcion', null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True, db_column='Fecha')),
                ('id_denuncia', models.ForeignKey(db_column='IdDenuncia', on_delete=django.db.models.deletion.CASCADE, to='api.denuncia')),
                ('id_usuario', models.ForeignKey(db_column='IdUsuario', on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
            options={
                'db_table': 'Votos',
                'constraints': [models.UniqueConstraint(fields=('id_usuario', 'id_denuncia'), name='uq_voto_usuario_denuncia')],
            },
        ),
    ]
