# Generated by Django 6.0.6 on 2026-06-19 00:39

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('id_usuario', models.BigAutoField(db_column='IdUsuario', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='NombreUsuario', max_length=150, unique=True)),
                ('password', models.CharField(db_column='ContraEncriptada', max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('is_active', models.BooleanField(db_column='Activo', default=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, db_column='FechaAlta')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'db_table': 'Usuarios',
                'ordering': ['username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='CarpetaArchivo',
            fields=[
                ('id_carpeta', models.BigAutoField(db_column='IdCarpeta', primary_key=True, serialize=False)),
                ('nombre_carpeta', models.CharField(blank=True, db_column='NombreCarpeta', max_length=255, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='FechaCreacion')),
            ],
            options={
                'verbose_name': 'carpeta de archivos',
                'verbose_name_plural': 'carpetas de archivos',
                'db_table': 'CarpetaArchivos',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(db_column='IdCategoria', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=150, unique=True)),
                ('descripcion', models.TextField(blank=True, db_column='Descripcion', null=True)),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
                'db_table': 'Categorias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_estado', models.AutoField(db_column='IdEstado', primary_key=True, serialize=False)),
                ('nombre_estado', models.CharField(db_column='NombreEstado', max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, db_column='Descripcion', null=True)),
            ],
            options={
                'verbose_name': 'estado',
                'verbose_name_plural': 'estados',
                'db_table': 'Estados',
                'ordering': ['nombre_estado'],
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(db_column='IdRol', primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(db_column='NombreRol', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'rol',
                'verbose_name_plural': 'roles',
                'db_table': 'Roles',
            },
        ),
        migrations.CreateModel(
            name='TagDenuncia',
            fields=[
                ('id_tag', models.AutoField(db_column='IdTag', primary_key=True, serialize=False)),
                ('nombre_tag', models.CharField(db_column='NombreTag', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
                'db_table': 'TagsDenuncia',
                'ordering': ['nombre_tag'],
            },
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id_usuario', models.OneToOneField(db_column='IdUsuario', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('legajo', models.CharField(blank=True, db_column='Legajo', max_length=50, null=True, unique=True)),
                ('fecha_ingreso', models.DateField(blank=True, db_column='FechaIngreso', null=True)),
                ('rol_admin', models.CharField(blank=True, db_column='RolAdmin', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'administrador',
                'verbose_name_plural': 'administradores',
                'db_table': 'Administradores',
            },
        ),
        migrations.CreateModel(
            name='InfoUsuario',
            fields=[
                ('id_usuario', models.OneToOneField(db_column='IdUsuario', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('domicilio', models.CharField(blank=True, db_column='Domicilio', max_length=255, null=True)),
                ('dni', models.CharField(blank=True, db_column='DNI', max_length=50, null=True, unique=True)),
                ('telefono', models.CharField(blank=True, db_column='Telefono', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'info de usuario',
                'verbose_name_plural': 'info de usuarios',
                'db_table': 'InfoUsuarios',
            },
        ),
        migrations.CreateModel(
            name='PreferenciaUsuario',
            fields=[
                ('id_usuario', models.OneToOneField(db_column='IdUsuario', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('recibir_emails', models.BooleanField(db_column='RecibirEmails', default=True)),
                ('idioma', models.CharField(db_column='Idioma', default='es', max_length=10)),
                ('zona_horaria', models.CharField(blank=True, db_column='ZonaHoraria', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'preferencias de usuario',
                'verbose_name_plural': 'preferencias de usuarios',
                'db_table': 'PreferenciasUsuario',
            },
        ),
        migrations.CreateModel(
            name='AuditCambio',
            fields=[
                ('id_audit', models.BigAutoField(db_column='IdAudit', primary_key=True, serialize=False)),
                ('tabla', models.CharField(blank=True, db_column='Tabla', max_length=100, null=True)),
                ('id_registro', models.CharField(blank=True, db_column='IdRegistro', max_length=100, null=True)),
                ('operacion', models.CharField(blank=True, db_column='Operacion', max_length=20, null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, db_column='FechaHora')),
                ('detalle_antes', models.JSONField(blank=True, db_column='DetalleAntes', null=True)),
                ('detalle_despues', models.JSONField(blank=True, db_column='DetalleDespues', null=True)),
                ('id_usuario', models.ForeignKey(blank=True, db_column='IdUsuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'registro de auditoría',
                'verbose_name_plural': 'registros de auditoría',
                'db_table': 'AuditCambios',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id_archivo', models.BigAutoField(db_column='IdArchivo', primary_key=True, serialize=False)),
                ('nombre_archivo', models.CharField(blank=True, db_column='NombreArchivo', max_length=255, null=True)),
                ('ruta', models.CharField(blank=True, db_column='Ruta', max_length=1024, null=True)),
                ('tipo_mime', models.CharField(blank=True, db_column='TipoMime', max_length=100, null=True)),
                ('tamano_bytes', models.BigIntegerField(blank=True, db_column='TamanoBytes', null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, db_column='FechaSubida')),
                ('id_carpeta', models.ForeignKey(db_column='IdCarpeta', on_delete=django.db.models.deletion.CASCADE, to='api.carpetaarchivo')),
            ],
            options={
                'verbose_name': 'archivo',
                'verbose_name_plural': 'archivos',
                'db_table': 'Archivos',
            },
        ),
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id_denuncia', models.BigAutoField(db_column='IdDenuncia', primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, db_column='Titulo', max_length=255, null=True)),
                ('descripcion', models.TextField(blank=True, db_column='Descripcion', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='FechaCreacion')),
                ('id_categoria', models.ForeignKey(blank=True, db_column='IdCategoria', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.categoria')),
                ('id_usuario', models.ForeignKey(db_column='IdUsuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('estado_actual', models.ForeignKey(blank=True, db_column='EstadoActualId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='denuncias_estado_actual', to='api.estado')),
            ],
            options={
                'verbose_name': 'denuncia',
                'verbose_name_plural': 'denuncias',
                'db_table': 'Denuncias',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='carpetaarchivo',
            name='id_denuncia',
            field=models.ForeignKey(db_column='IdDenuncia', on_delete=django.db.models.deletion.CASCADE, to='api.denuncia'),
        ),
        migrations.CreateModel(
            name='LogAcceso',
            fields=[
                ('id_log', models.BigAutoField(db_column='IdLog', primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, db_column='FechaHora')),
                ('ip', models.CharField(blank=True, db_column='IP', max_length=50, null=True)),
                ('user_agent', models.TextField(blank=True, db_column='UserAgent', null=True)),
                ('resultado', models.CharField(blank=True, db_column='Resultado', max_length=50, null=True)),
                ('id_usuario', models.ForeignKey(blank=True, db_column='IdUsuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'log de acceso',
                'verbose_name_plural': 'logs de acceso',
                'db_table': 'LogsAcceso',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id_notificacion', models.BigAutoField(db_column='IdNotificacion', primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, db_column='Tipo', max_length=50, null=True)),
                ('contenido', models.TextField(blank=True, db_column='Contenido', null=True)),
                ('leida', models.BooleanField(db_column='Leida', default=False)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, db_column='FechaEnvio')),
                ('id_usuario', models.ForeignKey(db_column='IdUsuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notificación',
                'verbose_name_plural': 'notificaciones',
                'db_table': 'Notificaciones',
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='TelefonoUsuario',
            fields=[
                ('id_telefono', models.BigAutoField(db_column='IdTelefono', primary_key=True, serialize=False)),
                ('telefono', models.CharField(blank=True, db_column='Telefono', max_length=50, null=True)),
                ('tipo', models.CharField(blank=True, db_column='Tipo', max_length=50, null=True)),
                ('principal', models.BooleanField(db_column='Principal', default=False)),
                ('id_usuario', models.ForeignKey(db_column='IdUsuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'teléfono de usuario',
                'verbose_name_plural': 'teléfonos de usuarios',
                'db_table': 'TelefonosUsuario',
            },
        ),
        migrations.CreateModel(
            name='EstadoDenuncia',
            fields=[
                ('id_estado_denuncia', models.BigAutoField(db_column='IdEstadoDenuncia', primary_key=True, serialize=False)),
                ('comentario_admin', models.TextField(blank=True, db_column='ComentarioAdmin', null=True)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True, db_column='FechaCambio')),
                ('id_denuncia', models.ForeignKey(db_column='IdDenuncia', on_delete=django.db.models.deletion.CASCADE, to='api.denuncia')),
                ('id_estado', models.ForeignKey(db_column='IdEstado', on_delete=django.db.models.deletion.CASCADE, to='api.estado')),
                ('id_admin', models.ForeignKey(blank=True, db_column='IdAdmin', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.administrador')),
            ],
            options={
                'verbose_name': 'historial de estado',
                'verbose_name_plural': 'historiales de estado',
                'db_table': 'EstadoDenuncias',
                'ordering': ['-fecha_cambio'],
            },
        ),
        migrations.CreateModel(
            name='DenunciaTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_denuncia', models.ForeignKey(db_column='IdDenuncia', on_delete=django.db.models.deletion.CASCADE, to='api.denuncia')),
                ('id_tag', models.ForeignKey(db_column='IdTag', on_delete=django.db.models.deletion.CASCADE, to='api.tagdenuncia')),
            ],
            options={
                'verbose_name': 'denuncia-tag',
                'verbose_name_plural': 'denuncias-tags',
                'db_table': 'DenunciaTags',
                'constraints': [models.UniqueConstraint(fields=('id_denuncia', 'id_tag'), name='uq_dt_denuncia_tag')],
            },
        ),
        migrations.CreateModel(
            name='UsuarioRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_rol', models.ForeignKey(db_column='IdRol', on_delete=django.db.models.deletion.CASCADE, to='api.rol')),
                ('id_usuario', models.ForeignKey(db_column='IdUsuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'usuario-rol',
                'verbose_name_plural': 'usuarios-roles',
                'db_table': 'UsuariosRoles',
                'constraints': [models.UniqueConstraint(fields=('id_usuario', 'id_rol'), name='uq_ur_usuario_rol')],
            },
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id_voto', models.BigAutoField(db_column='IdVoto', primary_key=True, serialize=False)),
                ('descripcion', models.TextField(blank=True, db_column='Descripcion', null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True, db_column='Fecha')),
                ('id_denuncia', models.ForeignKey(db_column='IdDenuncia', on_delete=django.db.models.deletion.CASCADE, to='api.denuncia')),
                ('id_usuario', models.ForeignKey(db_column='IdUsuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'voto',
                'verbose_name_plural': 'votos',
                'db_table': 'Votos',
                'ordering': ['-fecha'],
                'constraints': [models.UniqueConstraint(fields=('id_usuario', 'id_denuncia'), name='uq_voto_usuario_denuncia')],
            },
        ),
    ]
