# Generated by Django 6.0.6 on 2026-06-13 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrador',
            options={'verbose_name': 'administrador', 'verbose_name_plural': 'administradores'},
        ),
        migrations.AlterModelOptions(
            name='archivo',
            options={'verbose_name': 'archivo', 'verbose_name_plural': 'archivos'},
        ),
        migrations.AlterModelOptions(
            name='auditcambio',
            options={'ordering': ['-fecha_hora'], 'verbose_name': 'registro de auditoría', 'verbose_name_plural': 'registros de auditoría'},
        ),
        migrations.AlterModelOptions(
            name='carpetaarchivo',
            options={'verbose_name': 'carpeta de archivos', 'verbose_name_plural': 'carpetas de archivos'},
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nombre'], 'verbose_name': 'categoría', 'verbose_name_plural': 'categorías'},
        ),
        migrations.AlterModelOptions(
            name='denuncia',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'denuncia', 'verbose_name_plural': 'denuncias'},
        ),
        migrations.AlterModelOptions(
            name='denunciatag',
            options={'verbose_name': 'denuncia-tag', 'verbose_name_plural': 'denuncias-tags'},
        ),
        migrations.AlterModelOptions(
            name='estado',
            options={'ordering': ['nombre_estado'], 'verbose_name': 'estado', 'verbose_name_plural': 'estados'},
        ),
        migrations.AlterModelOptions(
            name='estadodenuncia',
            options={'ordering': ['-fecha_cambio'], 'verbose_name': 'historial de estado', 'verbose_name_plural': 'historiales de estado'},
        ),
        migrations.AlterModelOptions(
            name='infousuario',
            options={'verbose_name': 'info de usuario', 'verbose_name_plural': 'info de usuarios'},
        ),
        migrations.AlterModelOptions(
            name='logacceso',
            options={'ordering': ['-fecha_hora'], 'verbose_name': 'log de acceso', 'verbose_name_plural': 'logs de acceso'},
        ),
        migrations.AlterModelOptions(
            name='notificacion',
            options={'ordering': ['-fecha_envio'], 'verbose_name': 'notificación', 'verbose_name_plural': 'notificaciones'},
        ),
        migrations.AlterModelOptions(
            name='preferenciausuario',
            options={'verbose_name': 'preferencias de usuario', 'verbose_name_plural': 'preferencias de usuarios'},
        ),
        migrations.AlterModelOptions(
            name='rol',
            options={'verbose_name': 'rol', 'verbose_name_plural': 'roles'},
        ),
        migrations.AlterModelOptions(
            name='tagdenuncia',
            options={'ordering': ['nombre_tag'], 'verbose_name': 'tag', 'verbose_name_plural': 'tags'},
        ),
        migrations.AlterModelOptions(
            name='telefonousuario',
            options={'verbose_name': 'teléfono de usuario', 'verbose_name_plural': 'teléfonos de usuarios'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['nombre_usuario'], 'verbose_name': 'usuario', 'verbose_name_plural': 'usuarios'},
        ),
        migrations.AlterModelOptions(
            name='usuariorol',
            options={'verbose_name': 'usuario-rol', 'verbose_name_plural': 'usuarios-roles'},
        ),
        migrations.AlterModelOptions(
            name='voto',
            options={'ordering': ['-fecha'], 'verbose_name': 'voto', 'verbose_name_plural': 'votos'},
        ),
        migrations.AlterField(
            model_name='infousuario',
            name='email',
            field=models.EmailField(db_column='Email', max_length=255, unique=True),
        ),
    ]
