# Generated by Django 6.0.6 on 2026-06-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivo',
            name='archivo',
            field=models.FileField(blank=True, db_column='Archivo', null=True, upload_to='archivos/%Y/%m/'),
        ),
    ]
