# Generated by Django 6.0.6 on 2026-06-21 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_archivo_archivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvisoServicio',
            fields=[
                ('id_aviso', models.AutoField(db_column='IdAviso', primary_key=True, serialize=False)),
                ('titulo', models.CharField(db_column='Titulo', max_length=200)),
                ('descripcion', models.TextField(db_column='Descripcion')),
                ('categoria', models.CharField(db_column='Categoria', max_length=100)),
                ('fecha_inicio', models.DateTimeField(db_column='FechaInicio')),
                ('fecha_fin', models.DateTimeField(blank=True, db_column='FechaFin', null=True)),
                ('activo', models.BooleanField(db_column='Activo', default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='FechaCreacion')),
            ],
            options={
                'verbose_name': 'aviso de servicio',
                'verbose_name_plural': 'avisos de servicio',
                'db_table': 'AvisosServicio',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='AsistenciaEvento',
            fields=[
                ('id_asistencia', models.AutoField(db_column='IdAsistencia', primary_key=True, serialize=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, db_column='FechaRegistro')),
                ('id_usuario', models.ForeignKey(db_column='IdUsuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'asistencia a evento',
                'verbose_name_plural': 'asistencias a eventos',
                'db_table': 'AsistenciaEventos',
            },
        ),
        migrations.CreateModel(
            name='EventoComunidad',
            fields=[
                ('id_evento', models.AutoField(db_column='IdEvento', primary_key=True, serialize=False)),
                ('titulo', models.CharField(db_column='Titulo', max_length=200)),
                ('descripcion', models.TextField(blank=True, db_column='Descripcion', null=True)),
                ('ubicacion', models.CharField(db_column='Ubicacion', max_length=255)),
                ('fecha_evento', models.DateTimeField(db_column='FechaEvento')),
                ('imagen', models.ImageField(blank=True, db_column='Imagen', null=True, upload_to='eventos/%Y/%m/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='FechaCreacion')),
                ('asistentes', models.ManyToManyField(blank=True, related_name='eventos_asistidos', through='api.AsistenciaEvento', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'evento de comunidad',
                'verbose_name_plural': 'eventos de la comunidad',
                'db_table': 'EventosComunidad',
                'ordering': ['fecha_evento'],
            },
        ),
        migrations.AddField(
            model_name='asistenciaevento',
            name='id_evento',
            field=models.ForeignKey(db_column='IdEvento', on_delete=django.db.models.deletion.CASCADE, to='api.eventocomunidad'),
        ),
        migrations.AddConstraint(
            model_name='asistenciaevento',
            constraint=models.UniqueConstraint(fields=('id_usuario', 'id_evento'), name='uq_asistencia_usuario_evento'),
        ),
    ]
