# Generated by Django 6.0.6 on 2026-06-21 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_avisoservicio_asistenciaevento_eventocomunidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='equipo_asignado',
            field=models.IntegerField(blank=True, db_column='EquipoAsignado', null=True),
        ),
        migrations.AddField(
            model_name='denuncia',
            name='master_case',
            field=models.ForeignKey(blank=True, db_column='MasterCaseId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicados', to='api.denuncia'),
        ),
    ]
