# Generated by Django 6.0.6 on 2026-06-22 00:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_denuncia_equipo_asignado_denuncia_master_case'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id_equipo', models.AutoField(db_column='IdEquipo', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_column='FechaCreacion')),
                ('id_categoria', models.ForeignKey(db_column='IdCategoria', on_delete=django.db.models.deletion.CASCADE, to='api.categoria')),
            ],
            options={
                'verbose_name': 'equipo',
                'verbose_name_plural': 'equipos',
                'db_table': 'Equipos',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterField(
            model_name='denuncia',
            name='equipo_asignado',
            field=models.ForeignKey(blank=True, db_column='IdEquipo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='denuncias', to='api.equipo'),
        ),
        migrations.CreateModel(
            name='MiembroEquipo',
            fields=[
                ('id_miembro', models.AutoField(db_column='IdMiembro', primary_key=True, serialize=False)),
                ('dni', models.CharField(db_column='DNI', max_length=50)),
                ('cargo', models.CharField(db_column='Cargo', max_length=150)),
                ('id_equipo', models.ForeignKey(db_column='IdEquipo', on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to='api.equipo')),
            ],
            options={
                'verbose_name': 'miembro de equipo',
                'verbose_name_plural': 'miembros de equipo',
                'db_table': 'MiembrosEquipo',
            },
        ),
    ]
