# Generated by Django 5.2.17 on 2026-08-21 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_equipo_alter_denuncia_equipo_asignado_miembroequipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='infousuario',
            name='token_fcm',
            field=models.CharField(blank=True, db_column='Token_FCM', max_length=500, null=True),
        ),
    ]
